import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alquiler de ranchos en El Salvador</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-700 text-white py-8  
      bg-[url('../public/static/playa.jpg')] bg-cover 
       -z-10 bg-blend-soft-light backdrop-blur-md backdrop-contrast-100">
        <div className=' max-w-xl grid grid-cols-1 gap-8 m-10'>
      
          <h2 className="text-xl">
          Conviertete en un anfitrion
          </h2>

          <h2 className="text-5xl font-bold py-1">
          Comparte tu espacio, se parte del mundo
          </h2>

          <p className="py-4">
         Vemos a nuestros clientes como invitados a una fiesta y nosotros somos los anfitriones.
        Es nuestro trabajo cada dia mejorar un poco todo aspecto importante de la experiencia del cliente.
        </p>

          <button className = "bg-blue-500 py-2 px-6 text-lg rounded-md w-44">
              Enviar solicitud
        </button>
        
        </div>
      </div>
      <div className='py-2 m-10'>

        <h3>Comparte lo que amas</h3>

        <p>Gana dinero extra de manera responsable, invirtiendo en tu propiedad y haciendo mejor la experiencia de tus clientes</p>
      </div> 

    
    </div>
  )
}

export default Home
